### DISCUSSION TITLE
note deletion

### DISCUSSION THREAD

**Discussion by robbienohra** [zk-org/zk#188] [Help] [answered]
Is there a standard way to delete a note? I wasn't able to find anything on this in the documentation — it seems like we need to find the filename via an interactive edit and then manually delete the note?

**Comment by mickael-menu** [comment, marked as answer]
No there's no explicit delete command with `zk`, however you can add an alias that will delete the notes you select interactively:

`.zk/config.toml`
```toml
[alias]
rm = "zk list --interactive --quiet --format path --delimiter0 $@ | xargs -0 rm -vf --"
```

Then, you can run `zk rm`.
