### DISCUSSION TITLE
[Help] Can zk index multiple file extensions types at once?

### DISCUSSION THREAD

**Discussion by BananaJamJelly** [zk-org/zk#521] [Help]
### Verify

- [X] I searched the existing discussions for help

### How can we help you?

Hello,

In short, I've been trying to figure out if `zk` could `list` from multiple file extension types (notably, `.md` and `.txt` / `.todo.txt`).

I was hoping to include a group for [todo.txt files](https://github.com/todotxt/todo.txt) in the config file. I have a lot of todo lists I would like to organize, and thought it would be nice to have them listed with the rest of my notes in `zk`, but still be able to filter them if I wanted. It seems though that if in the config.toml the extension explicitly elected in `[note.extension]` doesn't match, it won't be indexed by `zk`.

There are a few workarounds for this, but all of them have draw backs for what I would like to do. For context, my workflow would look something like:
- make most of my notes on my desktop computer, and use Syncthing to sync them to my phone and laptop.
- Edit the files with `nvim` with a todo.txt plugin on PC, and use [Markor (a text editing app on Android)](https://github.com/gsantner/markor) on my phone.
- search and find files from termux and zk on my phone, and just zk on my computer

My goals would be:
- have nvim and markor differentiate between markdown and todo.txt files.
- have zk index both notes and my todo.txt lists, but be able to exclude todo.txt results when using `zk list`

Potential work arounds, I've thought of:
- create a separate zk notebook in a different directory which only uses todo.txt extensions (can't search my lists and notes simultaneously; need to maintain two zk directories)
- include a `vim: ft=todo` at the beginning of todo.txt files (so my nvim plugin will notice), but still use the `.md` file extension (Markor won't pick up and only looks at file extensions on my Phone, making todo lists difficult to edit and read)
<details>
<summary>below is my config.toml file:</summary>

```toml
[note]
language = "en"
filename = "{{id}}_{{slug title}}"
extension = "md"
template = "default.md"
id-charset = "alphanum"
id-length = 6
id-case = "lower"

[group.Food.log]
paths = ['Food/log']
[group.Food.log.note]
filename = "{{id}}_{format-date now '%F'}}_{{slug title}}"

[group.autorecipe]
[group.autorecipe.note]
template = "recipe.md"

[group.todo]
paths = ["todo", "todo/*"]

[group.todo.note]
filename = "{{format-date now '%F'}}_{{id}}_{{slug title}}"
extension = "todo.txt"
template = "todo.txt"

# [extra]

[format.markdown]
link-format = "markdown"
hashtags = true
colon-tags = false
multiword-tags = false

[tool]
editor = "/usr/bin/nvim"

[lsp]

[lsp.diagnostics]
dead-link = "error"

[lsp.completion]

[filter]
recents = "--sort created- --created-after 'last two weeks'"

[alias]
editlast = "zk edit --limit 1 --sort modified- $@"
scraperecipe = 'scrape-recipe.py "$1" "$3" | zk new -t "$2" --interactive -g autorecipe $ZKPATH/Food/Recipes'
ls = 'zk list -s modified -P -f oneline -x Food/Recipes -x papis/ $@'
lsdate = 'zk list -s modified -P -n 10 -f oneline -x Food/Recipes -x papis/ $@'
#recipes = 'zk edit -s created Food/Recipes -i $@'
recipes = 'zk list -s created -f oneline Food/Recipes $@'
path = 'zk list --quiet --format {{abs-path}} $@'

# https://github.com/zk-org/zk/discussions/188
rm = 'zk path --delimiter0 $@ | xargs -0 rm -vf --'
newdo = 'zk new -g todo $@'
```
</details>

Thank you.
