### DISCUSSION TITLE
Supporting YAML frontmatters for metadata

### DISCUSSION THREAD

**Discussion by mickael-menu** [zk-org/zk#618] [Ideas]
Many Zettelkasten use a YAML frontmatter to provide note metadata, e.g.:

```yaml
---
title: Improve the structure of essays by rewriting
date: 2011-05-16 09:58:57
keywords: [writing, essay, practice]
---
```

`zk` only supports `title`, we should support the rest as well:

* [x] ~~`date` for the creation date~~
* [x] ~~`keywords` and `tags` for tags~~
* [ ]  unknown keys could be saved and indexed for targeted search

[Neuron](https://neuron.zettel.page/metadata) also supports `unlisted: true` which could be interesting to disable indexing of particular notes.
