### ISSUE TITLE
zk list --created date, returns notes from one day after if YAML date does not have timestamp

### ISSUE THREAD

**Issue by tjex** [zk-org/zk#382]
### Check if applicable

- [X] I have searched the existing issues (**required**)
- [X] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

I created a daily note today (17th Jan). The system metadata via Finder shows that the file was created today, and the template for naming my daily notes uses `{{format-date now}}`, yet when I run `zk list --created=2024-01-17` the note is not returned.

It is returned if I run `zk list --created=2024-17-16`

```bash
$ zk list --created=2024-01-16
2024-01-17 d/2024/2024-01-17.md (16 hours ago)
```
Proof of date creation via `ll -l`

```bash
.rw-r--r-- tjex staff 935B Wed 17 Jan 2024-01-17.md
```

### How to reproduce?

1. Setup daily note conf as instructed [here](https://github.com/zk-org/zk/blob/main/docs/daily-journal.md)
2. create daily note and save
3. run `zk list --created=<the date today in YYYY-MM-DD format>
4. see if the daily note is returned or not

### zk configuration

```toml
[group.daily]
paths = ["d/2024"]

[group.daily.note]
filename = "{{format-date now}}"
extension = "md"

[alias]
daily = 'zk new --no-input "$ZK_NOTEBOOK_DIR/d/2024"'
```

### Environment

```bash
zk 0.14.0
system: Darwin 22.6.0 arm64
```
