### ISSUE TITLE
global template ignored

### ISSUE THREAD

**Issue by juanolon** [zk-org/zk#394]
### Check if applicable

- [X] I have searched the existing issues (**required**)
- [ ] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

Hello,
when i make a new note with `zk new` the [note].template entry in the config file is being ignored. i have the same entry on [group.custom.note].template for testing, and then works with `zk new --group custom`.

### How to reproduce?

1. `zk new`
2. expected template is not used

### zk configuration

```toml
[notebook]
dir = "~/notes"

[note]
language = "en"
# Template used to generate a note's filename, without extension.
filename = "{{id}}-{{format-date now '%Y-%m-%d'}}"

# The file extension used for the notes.
extension = "md"

template = "hugo.md"

# GROUP OVERRIDES
[group.custom.note]
template = "hugo.md"
```

### Environment

```bash
zk 0.14.0
system: Linux 6.1.0-18-amd64 x86_64 GNU/Linux
```
