### ISSUE TITLE
zk cli cannot search note modified or created at the same time

### ISSUE THREAD

**Issue by dtanphat9388** [zk-org/zk#404]
### Check if applicable

- [X] I have searched the existing issues (**required**)
- [ ] I'm willing to help fix the problem and contribute a pull request

### Describe the bug
I created 2 new note in yesterday and modified 3 other notes in today. I expected:
`zk list --created` return 2 results 
`zk list --modified` return 3 results 
`zk list --created "yesterday" --modified "today"` return 5 results 

### How to reproduce?

```sh
# return 2 note as expected
zk list --created="yesterday" -P -f "oneline"
# return 3 note as expected
zk list --modified="today" -P -f "oneline"

# but this filter return 0 result 
zk list --modified="today" --created="yesterday" -P -f "oneline"
```

### zk configuration

```toml
[note]
filename = "{{id}}"
template = "default.md"
ignore = [
   "drafts/*",
]
[format.markdown]

hashtags = true
colon-tags = false
multiword-tags = true


toml
[lsp]
[lsp.diagnostics]
dead-link = "error"
[lsp.completion]
[filter]
[alias]
conf = '$EDITOR "$ZK_NOTEBOOK_DIR/tech/.zk/config.toml"'
```
```


### Environment

```bash
zk 0.14.0
system: Linux 6.5.0-27-generic x86_64 GNU/Linux
```
