### ISSUE TITLE
`zk tag` doesn't shows numeric tags

### ISSUE THREAD

**Issue by Rooyca** [zk-org/zk#420]
### Check if applicable

- [X] I have searched the existing issues (**required**)
- [X] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

I have a file with this tag #2024 and when I use `zk tag` the tag is not displayed, if a change it for something like #2024/06 the tag appears. 

If I use :2024: it works. If I use #2024# it doesn't.

### How to reproduce?

1. Create a note with one of this tags: #2024 #2024#
2. Run `zk tag`
3. It doesn't show the tags

### zk configuration

```toml
[note]

template = "default.md"

[extra]


[format.markdown]

hashtags = true

colon-tags = true

multiword-tags = true

[tool]

[lsp]

[lsp.diagnostics]

dead-link = "error"

[lsp.completion]

[filter]

[alias]
```

### Environment

```bash
zk 0.14.0
system: Linux 6.9.3-arch1-1 x86_64 GNU/Linux
```
