### ISSUE TITLE
Slug title doesn't get populated into a filename

### ISSUE THREAD

**Issue by dodgog** [zk-org/zk#488]
### Check if applicable

- [X] I have searched the existing issues (**required**)
- [X] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

Fields {{title}} and {{slug-title}} have different behavior in templates and filenames.

### How to reproduce?

The template contains simply: `#{{title}}`.

When creating the note using `zk new area/poetry --title="abc"` a note with filename: `area/poetry/2025-01-08--s9p7.md` is created, however the note correctly contains `#abc`.

### zk configuration

```toml
[group.poetry]
paths = ["area/poetry"]
[group.poetry.note]
filename = "{{format-date now '%Y-%m-%d'}}-{{slug-title}}-{{id}}"
extension = "md"
template = poetry.md
```

### Environment

```bash
zk 0.14.1
system: Darwin 23.1.0 arm64
```
