### ISSUE TITLE
Overlapping group paths confusion

### ISSUE THREAD

**Issue by dodgog** [zk-org/zk#490]
### Check if applicable

- [X] I have searched the existing issues (**required**)
- [X] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

When one group defines a folder for its path, and another group defines as its path the subfolder of the folder, conflicts arise on creation of the note in the subfolder. It seems to randomly decide which group to assign the note to. 50% into folder's group, 50% into subfolders group.

### How to reproduce?

zk new --no-input "$ZK_NOTEBOOK_DIR/area/subfolder/"
zk new --no-input "$ZK_NOTEBOOK_DIR/area/subfolder/"

50% of the time this will create a notebook with the template 1 and 50% with the template 2.

### zk configuration

```toml
[group.area]
paths = ["area"]
[group.area.note]
extension = "md"
template = "template1.md"

[group.subarea]
paths = ["area/subfolder"]
[group.subarea.note]
extension = "md"
template = "template2.md"
```

### Environment

```bash
zk 0.14.1
system: Darwin 23.1.0 arm64
```
