### ISSUE TITLE
Error generating JSON via graph command

### ISSUE THREAD

**Issue by WhyNotHugo** [zk-org/zk#492]
### Check if applicable

- [x] I have searched the existing issues (**required**)
- [x] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

Previously discussed in https://github.com/zk-org/zk/issues/48

Generating a JSON graph fail with:

```
not a serializable argument for {{json}}: json: error calling MarshalJSON for type *core.lazyStringer: invalid character 't' after top-level value
```

### How to reproduce?

I can reproduce this with a single note: [qm4h.md](https://paste.sr.ht/blob/cd3ffe93a766f7d095c25ec85c1c229f963cf38b) (I picked on at random, it seems that most of my notes fail).

Run command `zk graph --format json > /dev/null`.

### zk configuration

```toml
I created a new notebook with a minimal config:


[note]
template = "default.md"
[extra]
[format.markdown]
hashtags = false
colon-tags = false
multiword-tags = false
[tool]
[lsp]
[lsp.diagnostics]
dead-link = "error"
[lsp.completion]
[filter]
[alias]
```

### Environment

```bash
zk-0.14.1-r3
Linux 6.12.8-0-edge x86_64 Linux
```
