### ISSUE TITLE
LSP is unable to resolve non-relative paths

### ISSUE THREAD

**Issue by winter-again** [zk-org/zk#494]
### Check if applicable

- [x] I have searched the existing issues (**required**)
- [ ] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

I'd like to use Markdown links relative to my notebook folder. Therefore, I set `link-format` to `[{{ title }}]({{ path }})`. The links seem to generate fine via autocomplete, but the LSP is unable to follow any of the links. I also get "not found" errors for all of these links. I expected the `link-format` setting to influence what kinds of links the LSP could resolve, but I could be wrong. Thanks.

### How to reproduce?

1. Use below config file, specifically the custom `link-format` value
2. Autocomplete a link
3. Note that LSP diagnostics give errors and trying to visit the link with LSP returns "No locations found"

### zk configuration

```toml
[note]

language = "en"

default-title = "Untitled"

extension = "md"

template = "default.md"

[extra]

[format.markdown]
link-format = "[{{ title }}]({{ path }})"
link-drop-extension = false
hashtags = true
colon-tags = false
multiword-tags = false

[tool]
editor = "nvim"
pager = "less -FIRX"
fzf-preview = "bat -p --color always {-1}"

[lsp]
[lsp.diagnostics]
dead-link = "error"

[lsp.completion]
note-label = "[{{ title }}]({{ path }})"
note-filter-text = "{{ title-or-path }}"

[filter]

[alias]
ls = "zk list $@"
editlast = "zk edit --limit 1 --sort modified- $@"
```

### Environment

```bash
zk 0.14.1
system: Linux 6.12.9-arch1-1 x86_64 GNU/Linux
```
