### ISSUE TITLE
Cannot open a new file in editor in Windows

### ISSUE THREAD

**Issue by apraga** [zk-org/zk#499]
### Check if applicable

- [x] I have searched the existing issues (**required**)
- [x] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

Hi,

`zk new --title "test"` fails to open the file in editor, even though the file is created.
```bash
Le chemin d’accès spécifié est introuvable. ("cannot find the path" in French)
zk: error: operation aborted by editor: hx.exe C:\Users\apraga\notes\m4jl.md: exit status 1
```
Tested on nushell and powershell, neovim and helix.

Thanks

### How to reproduce?

1. `zk new --title "test"` fails to open the file in editor 

### zk configuration

```toml
[note]
template = "default.md"

[format.markdown]

# Enable support for #hashtags.
hashtags = false
# Enable support for :colon:separated:tags:.
colon-tags = false
# Enable support for Bear's #multi-word tags#
# Hashtags must be enabled for multi-word tags to work.
multiword-tags = false


# EXTERNAL TOOLS
[tool]

# Default editor used to open notes. When not set, the EDITOR or VISUAL
# environment variables are used.
editor = "hx.exe"
[lsp]

[lsp.diagnostics]
# Each diagnostic can have for value: none, hint, info, warning, error

# Report titles of wiki-links as hints.
#wiki-title = "hint"
# Warn for dead links between notes.
dead-link = "error"
```

### Environment

```bash
zk 0.14.1-32-g87ac1cc
Windows 10
```
