### ISSUE TITLE
Timezone Issue

### ISSUE THREAD

**Issue by s5unty** [zk-org/zk#501]
### Check if applicable

- [x] I have searched the existing issues (**required**)
- [ ] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

The database stores absolute time in the GMT timezone, specifically in the file `cmd/new.go:L45`.
The `list` command outputs relative time, also using the GMT timezone, as implemented in `helpers/date.go:L56`.

Because of the difference between GMT and the local timezone, the relative time output by `list` is inaccurate.

Even changing `elapsed.Time` to `elapsed.LocalTime` does not seem to resolve the issue.
https://github.com/rvflash/elapsed/tree/v0.2.0

### How to reproduce?

```shell
# timedatectl | head -2
               Local time: 二 2025-01-28 16:51:48 CST
           Universal time: 二 2025-01-28 08:51:48 UTC

# zk p
... (exit)

# zk list -f oneline -s created-
... (8 hours ago)
```

### zk configuration

```toml
[alias]
p = "zk new --no-input --group p foo/$(cat /dev/urandom | tr -dc '0-9a-z' | head -c4 | tee /tmp/.zk | head -c1)"

[group.p]
path = ["foo"]
[group.p.note]
filename = "{{sh 'cat /tmp/.zk'}}"
```

### Environment

```bash
zk 0.14.1
system: Linux 6.8.0-51-generic x86_64 GNU/Linux
```
