### ISSUE TITLE
Can't find tags.

### ISSUE THREAD

**Issue by kirillov01** [zk-org/zk#548]
### Check if applicable

- [x] I have searched the existing issues (**required**)
- [ ] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

zk can't parse tags.

### How to reproduce?

`zk tag list`
Gives: `Found 0 tag`, even though I have dummy file and indexed my repo.

### zk configuration

```toml
[notebook]
dir = "~/notes"

[note]

extension="md"

[group.journal]
paths = ["journal/weekly", "journal/daily"]

[group.journal.note]
filename = "{{format-date now}}"

[format.markdown]
# Enable support for #hashtags
hashtags = true
# Enable support for :colon:separated:tags:
colon-tags = true

[tool]
editor="helix"
```

### Environment

```bash
zk 0.15.1
system: Linux 6.14.5-arch1-1 x86_64 GNU/Linux
```
